// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fhmrilaegwsvtpohijnh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZobXJpbGFlZ3dzdnRwb2hpam5oIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg0OTQ1NDIsImV4cCI6MjA3NDA3MDU0Mn0.29zfiHSi9CNm3JUh9JhxqngKocvMZBpjSioQUKU7qG8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});